name: Unit Tests

on: [pull_request, push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install .
    - name: Run unit tests
      run: |
        cd Tests
        python3 -m unittest discover -s . -t .
